export const data = [
	{
		id: 1,
		avatar: "/images/avatar-mark-webber.webp",
		name: "Mark Webber",
		reaction: "reacted to your recent post",
		time: "1m ago",
		action: "My first tournament today!",
		newNotification: true,
		isReaction: true,
	},
	{
		id: 2,
		avatar: "/images/avatar-angela-gray.webp",
		name: "Angela Gray",
		reaction: "followed you",
		time: "5m ago",
		newNotification: true,
	},
	{
		id: 3,
		avatar: "/images/avatar-jacob-thompson.webp",
		name: "Jacob Thompson",
		reaction: "has joined your group",
		action: "Chess Club",
		time: "1 day ago",
		newNotification: true,
	},
	{
		id: 4,
		avatar: "/images/avatar-rizky-hasanuddin.webp",
		name: "Rizky Hasanuddin",
		reaction: "sent you a private message",
		time: "5 days ago",
		isMessage: true,
		message:
			"Hello, thanks for setting up the Chess Club. I've been a member for a few weeks now and I'm already having lots of fun and improving my game.",
		newNotification: false,
	},
	{
		id: 5,
		avatar: "/images/avatar-kimberly-smith.webp",
		name: "Kimberly Smith",
		reaction: "commented on your picture",
		time: "1 week ago",
		image: "/images/image-chess.webp",
		picture: "/images/image-chess.webp",
		newNotification: false,
	},
	{
		id: 6,
		avatar: "/images/avatar-nathan-peterson.webp",
		name: "Nathan Peterson",
		reaction: "reacted to your recent post",
		action: "5 end-game strategies to increase your win rate",
		time: "2 weeks ago",
		isReaction: true,
		newNotification: false,
	},
	{
		id: 7,
		avatar: "/images/avatar-anna-kim.webp",
		name: "Anna Kim",
		reaction: "left the group",
		action: "Chess Club",
		time: "2 weeks ago",
		newNotification: false,
	},
];
